api:
  provider:
    name: "openai"  # "openai", "mistral", "voyage", "cohere"
    key: "your-api-key"
    model: "text-embedding-3-large"
  max_retries: 3
  retry_delay: 2

paths:
  input_folder: "/path/to/input/folder"
  output_base: "output"

processing:
  chunk_sizes: [400, 800, 1200]
  header_lines: 2

output:
  formats:
    - csv
    - json
    - npy
